### ISSUE TITLE
bootia32 file doesn't work

### ISSUE THREAD

**Issue by ghost** [gtbjj/x205ta#5]
Hi,

For quite a long time, I follow this tutorial and tried to boot on the arch USB install key with some unexpected results (generally with a boot on a unusable bash).

I found that the cause of this issue is the provided bootia32.efi file.

I made this tutorial like all the other times, but I use a bootia32.efi file[ from another arch on x205ta install guide](https://github.com/Mechazawa/Arch-Linux-Asus-F205TA), and everything works as expected.

(Although, the bootia32.efi file that you provide is quite large in comparison of the other architecture boot files, more than 4M for the provided file and less than 1M for default boot files)

Thanks again for your time.

**Comment by savagezen** [comment]
In regard to your [last comment in another issue](https://github.com/gtbjj/x205ta/issues/4), I re-wrote the first instructions.  Damn copy / paste demons got to me!

---

Hmm, I'm pretty sure I used that file not too long ago and it worked.  Anyway, the large size is due to [the method I used to compile](http://ifranali.blogspot.com/2015/04/installing-arch-linux-on-asus-x205ta.html).  The author's original, my original (first I ever compiled is the one currently on Git), and a fresh test one with the same method are all 4.5 - 4.6M.

The bootia32.efi you referenced is 608K and the one on my live system is 76K.  So, temporarily there's [a copy of my live bootia32.efi on Google Drive](https://drive.google.com/open?id=0B2RH_BSaD6YPRWhPZThaa3BmWm8).  If you want to give it a try and report back, then I'll upload that to Git if it's confirmed working.

**Comment by savagezen** [comment]
I have updated the file.  At some point I was desperately copy/pasting as I left "FS_LABEL" rather than the actual label of the filesystem in the grub.cfg.  Anyway, please see the [updated instructions](https://github.com/gtbjj/x205ta/blob/master/README.md) and [custom ISO I've rolled](https://drive.google.com/file/d/0B2RH_BSaD6YPWlJGV2xlSy1tcVU/view?usp=sharing)

**Comment by ghost** [comment]
Thanks a lot!

From what I found online searching with the error messages, it seems to be
an evidence of bad arch label.

It should be fine now.

**Comment by savagezen** [comment]
Yes, that was indeed the case.  So, make sure to label the drive (either with _mkfs_ or _rufus_) accordingly with the ISO version (e.g ARCH_201606).

If I am not able to post monthly update or if someone still wants to do things manually, [bootia32.efi](https://github.com/gtbjj/x205ta/raw/master/bootia32.efi) has been updated to work with the ARCH_201606 ISO.  If using a newer ISO, you'll need to update [grub.cfg](https://raw.githubusercontent.com/gtbjj/x205ta/master/grub_x205ta.cfg) in accordance with your ISO version and manually [create a bootia32.efi](https://wiki.archlinux.org/index.php/Asus_x205ta#Creating_bootia32.efi).
